/* eslint-disable */
/**
 * Generated data model types.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.11.0.
 *
 * This file is a mock for testing purposes.
 */

import type {
  DataModelFromSchema,
  DocumentByName,
  TableNamesInDataModel,
  SystemTableNamesInDataModel,
  Id,
} from "convex/server";
import type schema from "../schema.js";

/**
 * The `DataModel` type contains all the table definitions of your Convex app.
 */
export type DataModel = DataModelFromSchema<typeof schema>;

/**
 * The names of all of your app's tables.
 */
export type TableNames = TableNamesInDataModel<DataModel>;

/**
 * The type of a document in one of your app's tables.
 */
export type Doc<TableName extends TableNames> = DocumentByName<DataModel, TableName>;

/**
 * The type of a system table document.
 */
export type SystemDoc<TableName extends SystemTableNamesInDataModel<DataModel>> =
  DocumentByName<DataModel, TableName>;

/**
 * The type of a document ID.
 */
export type Id<TableName extends TableNames | SystemTableNamesInDataModel<DataModel>> =
  Id<TableName>;
