/* eslint-disable */
/**
 * Generated API models.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.11.0.
 *
 * This file is a mock for testing purposes.
 */
import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as sandbox from "../sandbox.js";
import type * as sessions from "../sessions.js";
import type * as toolRegistry from "../toolRegistry.js";
import type * as workspaces from "../workspaces.js";

/**
 * A type describing your app's public Convex API.
 *
 * This `api` export is used by the `ConvexHttpClient`, `ConvexReactClient`,
 * and `useQuery`/`useMutation`/`useAction` hooks to call your app's functions.
 *
 * When combined with `FilterApi`, it also describes the public interface
 * of your app's internal functions.
 */
export const api: FilterApi<
  ApiFromModules<{
    sandbox: typeof sandbox;
    sessions: typeof sessions;
    toolRegistry: typeof toolRegistry;
    workspaces: typeof workspaces;
  }>,
  FunctionReference<any, "public">
> = {} as any;

export const internal: FilterApi<
  ApiFromModules<{
    sandbox: typeof sandbox;
    sessions: typeof sessions;
    toolRegistry: typeof toolRegistry;
    workspaces: typeof workspaces;
  }>,
  FunctionReference<any, "internal">
> = {} as any;
